### ISSUE TITLE
Release v1.0.13 breaks CO2 sensor for *my* Pure A9

### ISSUE THREAD

**Issue by jesperll** [JohNan/homeassistant-wellbeing#76]
Latest release v1.0.13 broke CO2 sensor for *my* Pure A9 
I see a fix (#72) was merged for specifically that model but it looks like our models return different data. Might be firmware version specific.

Here's how my json looks like from the debug log:

```json
{
    "applianceData": {
        "applianceName": "Luftrenser",
        "created": "2024-02-03T16: 11: 15.5034292Z",
        "modelName": "PUREA9"
    },
    "properties": {
        "reported": {
            "FrmVer_NIU": "2.21",
            "Workmode": "Auto",
            "Fanspeed": 2,
            "UILight": true,
            "SafetyLock": false,
            "Ionizer": true,
            "FilterType": 99,
            "DspIcoTVOC": true,
            "ErrPM2_5": false,
            "ErrTVOC": false,
            "ErrTempHumidity": false,
            "ErrFanMtr": false,
            "ErrCommSensorDisplayBrd": false,
            "DoorOpen": false,
            "ErrRFID": false,
            "SignalStrength": "FAIR",
            "$version": 6,
            "PM1": 0,
            "PM2_5": 0,
            "PM10": 0,
            "Temp": 21,
            "Humidity": 54,
            "RSSI": -64,
            "CO2": 1018,
            "TVOC": 111
        }
    }
}
```

**Comment by WouterNordsiek** [comment]
Same here.

**Comment by PsychoV3** [comment]
CO2 sensor appears now to be eCO2....

**Comment by JohNan** [comment]
I see, it looks like like we probably need both then. If the attribute doesn't exist it shouldn't be visible anyhow. I'll add it back as soon as I can.

**Comment by JohNan** [comment]
I just pushed a new version. Let me know if it works now.

**Comment by WouterNordsiek** [comment]
> I just pushed a new version. Let me know if it works now. 

Unfortunately still not working for me. Ill try to check my logs .
